### ISSUE TITLE
Compiled under msvc 2019?

### ISSUE THREAD

**Issue by USSRcoder** [Ipotrick/Daxa#11]
Under win8, msvc2019, no clang, got error with template:
impl_device.cpp 186
```return CommandList{ManagedPtr{impl->command_list_recyclable_list.recycle_or_create_new(this->make_weak(), info).release()}};```
in these function : ```impl->command_list_recyclable_list.recycle_or_create_new(this->make_weak(), info).release()```

**Comment by USSRcoder** [comment]
this error fixed by commenting out ```-> std::unique_ptr<RecyclableT>``` in impl_recyclable_list.hpp#22
```auto recycle_or_create_new(ManagedWeakPtr device_impl, auto const & info) // -> std::unique_ptr<RecyclableT>```

**Comment by GabeRundlett** [comment]
very interesting. I don't know what the reason for this would be. I will check if I can repro here on Win11 with Visual Studio

**Comment by GabeRundlett** [comment]
Another thing to note is that I'm pretty sure VS2019 comes with clang. Are you sure you know which compiler you're using?

**Comment by Ipotrick** [comment]
Could you provide the exact error mvsc generates?

**Comment by GabeRundlett** [comment]
In Visual Studio 2019, I actually am surprised you were able to get that far with regards to the CMake. We're actually using some features that are technically from CMake version 3.21, which is just barely newer than the one provided from Visual Studio 2019. Is there a reason you're not using Visual Studio 2022?

**Comment by USSRcoder** [comment]
> Could you provide the exact error mvsc generates?

daxa\src\impl_device.cpp(186,121): error C2228: expression to the left of ".release" must represent a class, struct, or union
daxa\src\impl_device.cpp(186,121): message : type: std::unique_ptr<_Ty,std::default_delete<_Ty>>

if change it to 
```cpp
auto a = impl->command_list_recyclable_list.recycle_or_create_new(this->make_weak(), info);
return CommandList{ManagedPtr{a.release()}};
```
got 
daxa\src\impl_device.cpp(186,99): error C2514: "std::unique_ptr<_Ty,std::default_delete<_Ty>>": Cannot create class template.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(3415): message : see declaration "std::unique_ptr<_Ty,std ::default_delete<_Ty>>"

Windows 8, x64; SDK 8.1, or SDK 10.0.18362.0; VS2019 v142; /std:c++lastest

**Comment by USSRcoder** [comment]
> In Visual Studio 2019, I actually am surprised you were able to get that far with regards to the CMake. We're actually using some features that are technically from CMake version 3.21, which is just barely newer than the one provided from Visual Studio 2019. Is there a reason you're not using Visual Studio 2022?

Yes, everything seems to work in 2019. The new one is always harder, and why if everything works. And yes, they take up a lot of space. )

**Comment by Ipotrick** [comment]
I will close this issue as the part of code in question has been removed in a rescent refactoring.
