### ISSUE TITLE
Test 2 2 failed

### ISSUE THREAD

**Issue by USSRcoder** [Ipotrick/Daxa#12]
daxa_test_2_daxa_api_2_device.exe : 
[FAILURE]: terminator_CreateDevice: Failed in ICD C:\Windows\system32\\.\nvoglv64.dll vkCreateDevicecall
[[DAXA ASSERT FAILURE]]: validation error

msvc2019 (no clang), win8, VulkanSDK\1.3.224.1, Geforce 1060 6gb
I tried to fix it like here, there are errors along the chain, https://github.com/zeux/niagara/issues/18

Vulkan info : https://pastebin.com/wMUDUbmk

**Comment by GabeRundlett** [comment]
ICD stands for "Installable Client Driver". This sounds like an out-of-date driver issue. What driver version do you have? We require that your driver is Vulkan 1.3 compatible. I thought this would be checked in some way, but maybe not.

**Comment by USSRcoder** [comment]
VkPhysicalDeviceDriverProperties:
---------------------------------
	driverID        = DRIVER_ID_NVIDIA_PROPRIETARY
	driverName      = NVIDIA
	driverInfo      = 473.81

Downloaded yesterday, vk api also yesterday;
