### ISSUE TITLE
having trouble building

### ISSUE THREAD

**Issue by Popcorngaemrs** [Ipotrick/Daxa#33]
I am having trouble building Daxa, I dont know what I'm doing wrong

here is the message that I am getting

-- Running vcpkg install - done
-- The C compiler identification is MSVC 19.34.31935.0
-- The CXX compiler identification is MSVC 19.34.31935.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/VulkanTools/Daxa/build/cl-x86_64-windows-msvc/CMakeFiles/CMakeScratch/TryCompile-xs9yil

    Run Build Command(s):C:/Users/kamer/AppData/Roaming/Python/Python39/Scripts/ninja.exe cmTC_2cd02 && [1/2] Building C object CMakeFiles\cmTC_2cd02.dir\Debug\testCCompiler.c.obj
    [2/2] Linking C executable Debug\cmTC_2cd02.exe
    FAILED: Debug/cmTC_2cd02.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_2cd02.dir\Debug --rc=rc --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_2cd02.dir\Debug\testCCompiler.c.obj  /out:Debug\cmTC_2cd02.exe /implib:Debug\cmTC_2cd02.lib /pdb:Debug\cmTC_2cd02.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console -LIBPATH:C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1434~1.319\lib\x64   -LIBPATH:C:\PROGRA~2\WI3CF2~1\NETFXSDK\4.8\lib\um\x64   -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\lib\100220~1.0\ucrt\x64   -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\lib\100220~1.0\um\x64   -LIBPATH:C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1434~1.319\lib\x86\store\REFERE~1   -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\UNIONM~1\100220~1.0   -LIBPATH:C:\PROGRA~2\WI3CF2~1\10\REFERE~1\100220~1.0   -LIBPATH:C:\Windows\Microsoft.NET\Framework64\v4.0.30319 kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D C:\VulkanTools\Daxa\build\cl-x86_64-windows-msvc\CMakeFiles\CMakeScratch\TryCompile-xs9yil && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/dev/utils/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/VulkanTools/Daxa/build/cl-x86_64-windows-msvc/CMakeFiles/CMakeScratch/TryCompile-xs9yil/Debug/cmTC_2cd02.exe -installedDir C:/dev/utils/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
    'cmd.exe' is not recognized as an internal or external command,
    operable program or batch file.
    ninja: build stopped: subcommand failed.

**Comment by Ipotrick** [comment]
THis looks odd. I dont know from the top of my head what could cause this. It seems to not find cmd.exe for some reason. Can you run cmd.exe from your command line?
Gabe Rundlett probably has a better idea of what is going on. I pinged him i hope he has time this weekend.

**Comment by GabeRundlett** [comment]
This is strange for sure, but the problem comes when CMake is trying to test whether cl.exe (the Visual Studio compiler) is able to compile a simple C program. It failed immediately somehow - saying, as Patrick noted, that cmd.exe is missing... I doubt that.

This is not a resolution to the problem, but I'm curious - what happens if you try to build with clang? Switch the configure preset to be clang instead of cl

**Comment by Popcorngaemrs** [comment]
-- Running vcpkg install - done
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: A:/Strawberry/c/bin/gcc.exe
-- Check for working C compiler: A:/Strawberry/c/bin/gcc.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler

    "A:/Strawberry/c/bin/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/VulkanTools/Daxa/build/clang-x86_64-windows-msvc/CMakeFiles/CMakeScratch/TryCompile-yym15x

    Run Build Command(s):C:/Users/kamer/AppData/Roaming/Python/Python39/Scripts/ninja.exe cmTC_5280a && [1/2] Building C object CMakeFiles/cmTC_5280a.dir/Debug/testCCompiler.c.obj
    [2/2] Linking C executable Debug\cmTC_5280a.exe
    FAILED: Debug/cmTC_5280a.exe
    cmd.exe /C "cd . && A:\Strawberry\c\bin\gcc.exe -g  CMakeFiles/cmTC_5280a.dir/Debug/testCCompiler.c.obj -o Debug\cmTC_5280a.exe -Wl,--out-implib,Debug\libcmTC_5280a.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cmd.exe /C "cd /D C:\VulkanTools\Daxa\build\clang-x86_64-windows-msvc\CMakeFiles\CMakeScratch\TryCompile-yym15x && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/dev/utils/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/VulkanTools/Daxa/build/clang-x86_64-windows-msvc/CMakeFiles/CMakeScratch/TryCompile-yym15x/Debug/cmTC_5280a.exe -installedDir C:/dev/utils/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
    'cmd.exe' is not recognized as an internal or external command,
    operable program or batch file.
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:18 (project)

**Comment by GabeRundlett** [comment]
Somehow, in this build log, it's saying it's trying to use GCC (and clearly you're on Windows) but it says the same thing when GCC fails. 

I have never seen that as an issue, what happens if you press WindowsKey+R and type cmd in there, then press enter?

**Comment by Popcorngaemrs** [comment]
it brings up it opens the command prompt

**Comment by GabeRundlett** [comment]
Yeah.. that's what should happen. WTF is going on with your build system XD

**Comment by Popcorngaemrs** [comment]
idk 3-4 years of me adding random stuff

**Comment by GabeRundlett** [comment]
What exactly are you doing to trigger the build? Command line? CMake extension from vscode? Clion? Visual Studio CMake support?

**Comment by Popcorngaemrs** [comment]
I have tried cmd, powershell and vscode all the same

**Comment by Popcorngaemrs** [comment]
i just removed a ton of old stuff from path and now im getting this

-- Running vcpkg install - done
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:18 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:18 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

**Comment by GabeRundlett** [comment]
That's because  `cl` was stored in the CMake cache file as the c++ compiler, but now it's not in path. Delete the CMakeCache.txt file that is within the build folder - or just delete the whole build folder to be more safe than sorry

**Comment by Popcorngaemrs** [comment]
i think that put me right back where i started


-- Running vcpkg install - done
-- The C compiler identification is MSVC 19.34.31935.0
-- The CXX compiler identification is MSVC 19.34.31935.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/VulkanTools/Daxa/build/cl-x86_64-windows-msvc/CMakeFiles/CMakeScratch/TryCompile-pdx5eq

    Run Build Command(s):C:/Users/kamer/AppData/Roaming/Python/Python39/Scripts/ninja.exe cmTC_bb70a && [1/2] Building C object CMakeFiles\cmTC_bb70a.dir\Debug\testCCompiler.c.obj
    [2/2] Linking C executable Debug\cmTC_bb70a.exe
    FAILED: Debug/cmTC_bb70a.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_bb70a.dir\Debug --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_bb70a.dir\Debug\testCCompiler.c.obj  /out:Debug\cmTC_bb70a.exe /implib:Debug\cmTC_bb70a.lib /pdb:Debug\cmTC_bb70a.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console -LIBPATH:C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1434~1.319\lib\x64   -LIBPATH:C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1434~1.319\lib\x86\store\REFERE~1   -LIBPATH:C:\Windows\Microsoft.NET\Framework64\v4.0.30319 kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D C:\VulkanTools\Daxa\build\cl-x86_64-windows-msvc\CMakeFiles\CMakeScratch\TryCompile-pdx5eq && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/dev/utils/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/VulkanTools/Daxa/build/cl-x86_64-windows-msvc/CMakeFiles/CMakeScratch/TryCompile-pdx5eq/Debug/cmTC_bb70a.exe -installedDir C:/dev/utils/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_bb70a.dir\Debug/manifest.res CMakeFiles\cmTC_bb70a.dir\Debug/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.

**Comment by GabeRundlett** [comment]
nope, it didn't! You're farther this time. It says that RC (the visual studio resource compiler) failed to compile a resource. (this tool is used - for example - to compress and pack icons into the executable, you know, when there's an icon on the .exe file itself)

I might suggest you try re-installing Visual Studio 2022

**Comment by Popcorngaemrs** [comment]
ill give that a try

**Comment by Popcorngaemrs** [comment]
I believe I found the problem, my command prompt is broken, it will not do anything if it is not in administrator mode
so i built it on another computer

**Comment by GabeRundlett** [comment]
Alright, let me know if you have any other issues that pertain to Daxa! Good luck
