### ISSUE TITLE
A vkGetQueryPoolResults() stride of zero is probably not what you want?

### ISSUE THREAD

**Issue by pdaniell-nv** [Ipotrick/Daxa#34]
While looking into another issue, I noticed this:
https://github.com/Ipotrick/Daxa/blob/b988e42202e296c3b393b6d0c84c9ad1aaf3aa8a/src/impl_timeline_query.cpp#L31

I don't think using stride=0 for vkGetQueryPoolResults() when count>1 is what you want since then the last result value written will go to slot zero and overwrite all the other results.

**Comment by Ipotrick** [comment]
@MatejSakmary is looking into it.

**Comment by MatejSakmary** [comment]
I fixed the issue. Thank you for letting us know :)

**Comment by pdaniell-nv** [comment]
Wow, that was quick. I wonder if line 29 is also wrong: `count * sizeof(u64),` for the size. Should this be `count * sizeof(u64) * 2`?

**Comment by GabeRundlett** [comment]
Principle Engineer at NVIDIA commenting on our library? Awesome.
Thank you for reviewing our code! You're right, that should be `* 2`. I'm surprised that the validation layers didn't catch these things, at least with a warning!! Matej is fixing it right now

**Comment by MatejSakmary** [comment]
Fixed, thank you again! Very surprised validation didn't complain at all...

**Comment by GabeRundlett** [comment]
Interesting note @pdaniell-nv, we tested after making the stride change you suggested, and somehow the whole array was still written out. I would guess that internally it's ignoring the size parameter, which can be done since it *can* just multiply `stride * queryCount` to get the size to write out. I would have guessed that validation checks whether the `dataSize` provided is big enough to fit `stride * queryCount`

**Comment by pdaniell-nv** [comment]
What version of VVL are you using? I think the latest 1.3.236.0 should catch the `size` bug.

The reason I happened to be looking at this is because of another issue reported to me with Renderdoc and GTX 980. Running the "daxa_test_2_daxa_api_3_command_list" test in Renderdoc causes a device lost. I'm looking into that now, and it appears to be a driver bug.

**Comment by MatejSakmary** [comment]
Oh nvm VVL version 1.3.231 catch the error. I didn't see this because I didn't use vkconfig to properly enable the validation layers. I need to get into the habit of enabling them using vkconfig more...

**Comment by Ipotrick** [comment]
> What version of VVL are you using? I think the latest 1.3.236.0 should catch the `dataSize` bug.
> 
> The reason I happened to be looking at this is because of another issue reported to me with Renderdoc and GTX 980. Running the "daxa_test_2_daxa_api_3_command_list" test in Renderdoc causes a device lost. I'm looking into that now, and it appears to be a driver bug.

Is that bug related to device local host visible memory by any chance?

**Comment by pdaniell-nv** [comment]
> Is that bug related to device local host visible memory by any chance?

Yes it is.

**Comment by Ipotrick** [comment]
Ah, thanks for taking a look at this!
