### ISSUE TITLE
Can't compile project.

### ISSUE THREAD

**Issue by Stanlyhalo** [Ipotrick/Daxa#37]
Hello, I compiled daxa from the latest repo version in both debug & release on windows with the presets being: cl-x86_64-windows-msvc-debug, and cl-x86_64-windows-msvc-release. I finally think I got daxa implemented, however I get this error when compiling from my project: 
![image](https://user-images.githubusercontent.com/36088749/211713122-56b1fa33-52fc-4af6-b0be-5814235586b3.png)

I'm not super familiar with cmake, I only use it to compile libraries to use in my projects so I don't know if there's some command line argument I need to add that was stated in the wiki.

**Comment by GabeRundlett** [comment]
I totally recommend not trying to do things manually, the library is meant to be consumed as a package through CMake and vcpkg.
If you *really* need to do things this way, the issue you're facing is that there are #defines that are added to the build via CMake when using the package in the correct way. As long as you compiled the original CMake project as having utils enabled, you should be able to add the utils #define to your build to make it work. This #define of `DAXA_BUILT_WITH_UTILS` needs to equal `1`

**Comment by GabeRundlett** [comment]
Using any of the existing CMakePresets (as you said you did) that build flag should be enabled already. So basically all you need to do is add that define. For Visual Studio, that just means going to YOUR project properties, and adding a preprocessor definition like so:
![image](https://user-images.githubusercontent.com/28205981/211714765-63c16fc2-8f05-4b8f-9c61-53b7758d27cc.png)

**Comment by Stanlyhalo** [comment]
Ah thank you for the help, it seemed to resolve that issue, I'll close this as solved now, thanks so much. Just gotta fix my other compiler errors now lol.

**Comment by GabeRundlett** [comment]
Alright! Feel free to open another issue if you need anything.
