### ISSUE TITLE
Unresolved external symbols.

### ISSUE THREAD

**Issue by Stanlyhalo** [Ipotrick/Daxa#38]
Hello, it's me again, I'm still trying to implement daxa into my project, however I came across some external symbol errors. It's referencing imgui, fsr2, and something relating to the pipeline.
![image](https://user-images.githubusercontent.com/36088749/211835483-88a982cc-077a-449d-9f64-d2a36d3159e6.png)

Some things to note: I don't want to use imgui, so I was hoping there was some define statement I could use to exclude it, but found no luck, so I even tried to remove the imgui from the src in the cloned repo, and remove the references to imgui and that file in the cmake lists file, however when recompiling I get an error referencing pthreads.lib and pthead.lib (the error refers to not being able to link to it). This error only occurs when removing imgui files from the cloned repo.

**Comment by GabeRundlett** [comment]
ImGui, FSR2, GLSLANG and DXC are all dependencies of Daxa's UTILS - which are not part of the core library. You built with UTILS enabled, which I actually very much-so recommend, I just have not yet made it modular enough for this situation.

The reason you mainly want Daxa's UTILS is because of Task List, which allows you to compile a sequence of tasks with their listed dependencies into an optimally synchronized sequence of commands. Of course, the PipelineManager is also useful, if you don't want to compile SPIR-V yourself.

**Comment by GabeRundlett** [comment]
I'm working on making it more modular right now

**Comment by Stanlyhalo** [comment]
Oh wow, thanks for the extensive reply. Thanks for all the in-depth information. I tried removing the imgui related file and the two references in the cmakelists that relates to either the file or imgui, however I get issues of it trying to link pthreads and pthread lib files. I really like how you're making it more modular, coming from some Vulkan experience this library does seem so simple yet so extensive in what I can customize so I hope I can implement this. The only thing I don't want is imgui rn, I would like to keep fsr2 and the hlsl compiler so I'll figure those out next, K have a friend with data experience who's helping me. I'll leave this open just in case I missed something with trying to strip imgui from daxa.

**Comment by GabeRundlett** [comment]
You're building on Windows, correct? Could you give me a bit more info about what you tried for disabling ImGUI, and maybe screenshots of the errors? This modularization re-work should be done in the next couple hours

**Comment by GabeRundlett** [comment]
That's a very very odd error to get. There's no reason it should be trying to check if pthreads exists, especially if you already built the repo before... Very perplexing, for sure. Hopefully this is a fluke and doesn't happen after I push this modularization

**Comment by Stanlyhalo** [comment]
Yeah, that's actually what I said to my friend lol. I'm fine with waiting however long it takes to modularize the project, I really enjoy how easily daxa looks to utilize.

**Comment by GabeRundlett** [comment]
I just pushed the change to Daxa that should allow you to just modify the CMakePresets.json file in order to build without ImGui.
revert your changes inside the CMakeLists.txt file where you manually disabled ImGui, pull the latest changes, and set both the ImGui util flag to false, as well as the tests flag. You want to not try to build the tests, since some rely on ImGui.
![image](https://user-images.githubusercontent.com/28205981/211870797-8b4475a6-2a00-486c-8af7-074224de95a6.png)

Note that the headers have been changed, so you should update the ones you're using in the build tree to use the new ones!
Now you need to add new defines to your project, INSTEAD of the old `DAXA_BUILT_WITH_UTILS=1` one. (This old one can be removed)

You should add the following:
`DAXA_BUILT_WITH_UTILS_FSR2=1`
`DAXA_BUILT_WITH_UTILS_MEM=1`
`DAXA_BUILT_WITH_UTILS_PIPELINE_MANAGER_GLSLANG=1`
`DAXA_BUILT_WITH_UTILS_PIPELINE_MANAGER_DXC=1`
`DAXA_BUILT_WITH_UTILS_TASK_LIST=1`

**Comment by Stanlyhalo** [comment]
Hmm, I pulled the changes, and set both imgui and tests to false, however it seems I get these errors when trying to run `cmake --build --preset=cl-x86_64-windows-msvc-debug`:
[err.txt](https://github.com/Ipotrick/Daxa/files/10394629/err.txt)

It seems it thinks certain definitions are set to false. I'm assuming I probably did something wrong, however there's nothing to indicate what I did (it's just exactly the new commit with tests & imgui set to false)

**Comment by GabeRundlett** [comment]
Those are errors coming from the tests. Make sure it's actually set to false, saved, and try building again. If it doesn't build again, try deleting the build folder, and trying again.

**Comment by Stanlyhalo** [comment]
Oh okay, I just noticed if I delete the debug & release lib files, they do generate, and it does seem from the directory it is the tests it's trying to generate, and now all I have left to solve are these:
![image](https://user-images.githubusercontent.com/36088749/211877835-d82be6d0-591e-4d1c-8671-18e281bc8e8a.png)

Thanks for the help so far by the way, that was a really helpful commit in my case.

**Comment by GabeRundlett** [comment]
I'm not sure here. Those symbols should definitely exist in the binary. Are you sure you're linking to the newly compiled binary?

**Comment by Stanlyhalo** [comment]
I'm positive, I replaced the lib files and even made sure the include was updated, and made sure to add the preprocessor definitions, maybe that error from the daxa build is causing an issue... I tried deleting the build folder however when trying to run `cmake ..` in it before running the build with the specific configuration, it seems to not be able to find the unofficial vulkan memory library (or whatever it's called). And if I just try to run the command to build the debug/release, it just says those directories do not exist (which didn't happen before).

**Comment by Stanlyhalo** [comment]
If I forcefully add the `cl-x86_64-windows-msvc` folder, it just says it couldn't load the cache.

**Comment by GabeRundlett** [comment]
okay. Remove the build folder, and run the configure command first
(in the repo root folder)
`cmake --preset=cl-x86_64-windows-msvc`
and then the build commands
`cmake --build --preset=cl-x86_64-windows-msvc-debug`
`cmake --build --preset=cl-x86_64-windows-msvc-release`

**Comment by Stanlyhalo** [comment]
Ah your right, I completely forgot I had to set the preset before the build. I still have these errors:
![image](https://user-images.githubusercontent.com/36088749/211880656-94c30ef0-e186-4fd0-9081-1bf76b8f5042.png)

However, as for now, I can probably disable fsr2 until I want to add it, but the last ones still might pose an issue even after disabling fsr2.

**Comment by Stanlyhalo** [comment]
Disabled fsr2 for now, however I got this which idk how to fix, as it seems to refer to the pipeline manager.
![image](https://user-images.githubusercontent.com/36088749/211881144-41749b43-39f3-4fa8-bd70-8149aae510c4.png)

**Comment by GabeRundlett** [comment]
You need to link to DXC to use the HLSL portion of the Pipeline Manager utility. Or, you can disable that for now as well.

**Comment by GabeRundlett** [comment]
We pull in this dependency though vcpkg. I created this package, so it's in my vcpkg-registry repo, but from that package script, you can see that it's pulled in from their GitHub releases page, here: https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.6.2112/dxc_2021_12_08.zip

it might also exist in the Vulkan SDK, which is where we acquire it from on Linux

**Comment by Stanlyhalo** [comment]
Alright, thanks, for now I'll just disable it.

And it compiles successfully, I'll make this as close now, thank you for the help so much. I'll slowly add back fsr2 and support for hlsl once I get my engine back up to my standards. For now I just need to solve my other error (runtime error) possible due to just loading a model or doing something wrong. Again, thanks for the help so much.

**Comment by GabeRundlett** [comment]
For the future, I'll let you know what the build process is for FSR2 for us. FSR2 is also a library that I added as a vcpkg package in my own registry. It's just compiling the subdirectory `src/ffx-fsr2-api` of the official FSR2 repository https://github.com/GPUOpen-Effects/FidelityFX-FSR2 at the 2e6d42ad0a6822c934ffc6121c1e9541af870777 hash (before FSR2.1)

In my registry, you can see that I just completely replace that `CMakeLists.txt` in `src/ffx-fsr2-api`, and do the build inside there
https://github.com/GabeRundlett/vcpkg-registry/blob/master/ports/fsr2/2.0.0/portfile.cmake

**Comment by Ipotrick** [comment]
Just as a comment on the side, daxas glsl integration is much better then hlsl integration.
