### ISSUE TITLE
Shader Insanity with task list

### ISSUE THREAD

**Issue by Ipotrick** [Ipotrick/Daxa#45]
Integrate shader compilatiuon with task list.
Shader declares use of a task list resource.
Task list will inferr that use and add the corresponding task.
No more need to pass task resources around, they simply become a global in the shader after usage declaration.

Syntax proposal:

```glsl

DAXA_DECLARE_TASK_IMAGE_USE(task_image_debug_name, access, slice);

void main()
{
  daxa_Image2Df32 image = task_image_debug_name;
}
```

**Comment by Ipotrick** [comment]
It would be nice to have a way to make the slice run-time configurable.

**Comment by GabeRundlett** [comment]
I'm not convinced I like it yet, and would like to see it implemented first

**Comment by Ipotrick** [comment]
Merged changes that allow for task use declaration in inl files.
