### ISSUE TITLE
Impossible to create Tasklist without staging pool memory

### ISSUE THREAD

**Issue by MatejSakmary** [Ipotrick/Daxa#51]
When you assign 0 to `staging_memory_pool_size` in` TaskListCreateInfo` Daxa errors out because it attempts to create 0-sized buffer which is caught by the internal validation as an error.

**Comment by MatejSakmary** [comment]
To expand on this, because (from what I understand) staging memory is used by TaskList implementation to copy data into constant buffers - It would be a good idea to notify the user that the staging buffer is too small instead of crashing :D

**Comment by Ipotrick** [comment]
done
