### ISSUE TITLE
Using unsupported daxa::PresentMode::MAILBOX causes VK_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by OmniSudo** [Ipotrick/Daxa#61]
`
daxa::Swapchain::acquire_next_image() impl_swapchain.cpp:54
`

There is an assert that fails when using an unsupported present mode.

**Comment by Ipotrick** [comment]
Added better error messages for this case.
Added device function to check for present mode support.
4a2bb994dfa6cf7b8fede85e25f18dddfde8b88b
