### ISSUE TITLE
Daxa crashes when creating an image with format R8G8B8_UNORM

### ISSUE THREAD

**Issue by Jaisiero** [Ipotrick/Daxa#69]
It looks like my Nvidia driver crashes when daxa calls _vkCreateImage_  using that image format:

**Unhandled exception at 0x00007FFDABC81A1B (nvoglv64.dll) in daxa-lod.exe: 0xC0000094: Integer division by zero.**

![image](https://github.com/Ipotrick/Daxa/assets/6051981/7583328d-f1c1-48b6-a334-46fac74032ac)

Which it doesn't occur when I use other format like *R8G8B8A8_UNORM*

And this is the call stack:
![image](https://github.com/Ipotrick/Daxa/assets/6051981/b01c9da5-94b5-4efe-852a-4518af458ecb)

This is my code before the crash:
```
ImageTexture red_brick_wall = ImageTexture(RED_BRICK_WALL_IMAGE);
daxa_u32 SIZE_X = red_brick_wall.get_width();
daxa_u32 SIZE_Y = red_brick_wall.get_height();
daxa_u32 SIZE_Z = 1;

daxa_u32 image_stage_buffer_size = red_brick_wall.get_size();

images.push_back(device.create_image({
    .dimensions = 2,
    .format = daxa::Format::R8G8B8_UNORM, // change format for R8G8B8A8_UNORM and it doesn't crash
    .size = {SIZE_X, SIZE_Y, SIZE_Z},
    .usage = daxa::ImageUsageFlagBits::SHADER_STORAGE | daxa::ImageUsageFlagBits::TRANSFER_DST | daxa::ImageUsageFlagBits::SHADER_SAMPLED,
    .name = "image_2",
}));
```

Let me know if you need more info.
Cheers.

**Comment by Ipotrick** [comment]
its because your gpu doesnt support R8G8B8_UNORM. GPUs basically dont support any formats that are not a power of two size for each texel. R8G8B8 is 24 bit so non pot. 
We could add a check for image format compat but i would think validation finds this no?

**Comment by Jaisiero** [comment]
Oh right! I didn't realize that.
![image](https://github.com/Ipotrick/Daxa/assets/6051981/186836da-e523-4de5-b9c0-0d6db379556d)

So many format and it just support a few of them. 

And yes, you are totally right it throws a validation error:

```
VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251(ERROR / SPEC): msgNum: -1094930823 - Validation Error: [ VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251 ] | MessageID = 0xbebcae79 | vkCreateImage(): The following parameters -
format (VK_FORMAT_R8G8B8_UNORM)
type (VK_IMAGE_TYPE_2D)
tiling (VK_IMAGE_TILING_OPTIMAL)
usage (VK_IMAGE_USAGE_TRANSFER_DST_BIT|VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_STORAGE_BIT)
flags (VkImageCreateFlags(0))
returned (VK_ERROR_FORMAT_NOT_SUPPORTED) when calling VkGetPhysicalDeviceImageFormatProperties2. The Vulkan spec states: Each of the following values (as described in Image Creation Limits) must not be undefined : imageCreateMaxMipLevels, imageCreateMaxArrayLayers, imageCreateMaxExtent, and imageCreateSampleCounts (https://vulkan.lunarg.com/doc/view/1.3.261.0/windows/1.3-extensions/vkspec.html#VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251)
```

So yep my bad. do you think that could be check runtime?
Thanks!
