### ISSUE TITLE
Device Creation

### ISSUE THREAD

**Issue by Ipotrick** [Ipotrick/Daxa#80]
Device creation has problems:
* there is no way to read physical device properties and choose without the callback to create a device
* there are no/ poor errors for device creation failure

My idea would be to remove the device selector in device creation.
Instead make it a free function that takes a physical device list from the daxa instance.

It might also be nice if device creation wouldnt fail when a feature is not present and instead make it the user responsibility to check if a created device can actually do what is asked of it. This might be misleading but also more convenient to program.

**Comment by Ipotrick** [comment]
A scenario i had encountered was mesh shading support.
Many times the features used are a hard requirement and then the current daxa device creation is fine.
But when one wants to have a fallback path (for example a for mesh shading) then its hard/impossible to do that with current daxa device creation.

**Comment by Ipotrick** [comment]
There is also the point that some devices dont support daxa at all.
In that case we should emit a good error message, collecting all the features/properties missing for that device.

**Comment by loopunit** [comment]
I also have the need to create a device based on its id (no other way to associate a device with a specific desktop on windows), which I've gone ahead and added [here](https://github.com/loopunit/Daxa/commit/abc0f9a516353a924fb899a5981751ea941fc07c) since it was a blocker when I was evaluating this lib.

**Comment by Ipotrick** [comment]
Device creation is redone in 3.1
