### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ShinySilver** [Ipotrick/Daxa#86]
Somehow, I get an error during compilation on Linux:
![image](https://github.com/Ipotrick/Daxa/assets/36570018/8bd9edf5-05e7-40bf-9305-9fc32b026880)

The error is caused by a macro called "None" already existing. I could not find what defined this macro in my system, so I avoided the issue by adding "ifdef None", "undef None", "endif" line 100 in types.hpp.

gcc version and build logs below.
![image](https://github.com/Ipotrick/Daxa/assets/36570018/9579b20a-a57d-4e89-8aa2-42495d2694a1)
[install-x64-linux-dbg-out.log](https://github.com/Ipotrick/Daxa/files/14908565/install-x64-linux-dbg-out.log)

**Comment by GabeRundlett** [comment]
Thanks for this info! This shouldn't happen and is a bug. I think I know how to fix it.

**Comment by GabeRundlett** [comment]
Should be fixed with https://github.com/Ipotrick/Daxa/commit/ed6318ab3d15f7dd6dc92cd6e4700be22fd382d0

**Comment by ShinySilver** [comment]
It works. Thanks :)
