### ISSUE TITLE
DAXA_RESULT_NO_SUITABLE_DEVICE_FOUND using NVIDIA Quadro P2200

### ISSUE THREAD

**Issue by JulienHemminger** [Ipotrick/Daxa#91]
I use Ubuntu / Linux. I am trying to execute the [GVox Engine](https://github.com/GabeRundlett/gvox_engine) which uses Daxa.
When building and executing according to the GVox Engine's README, I get the following error message:
```
[[DAXA ASSERT FAILURE]]: error code: DAXA_RESULT_NO_SUITABLE_DEVICE_FOUND(1073741862), failed to create device.

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
```

My GPU is a [NVIDIA Quadro P2200](https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro-product-literature/quadro-p2200-datasheet-letter-974207-r4-web.pdf).

Does Daxa require a GPU of NVIDIAS RTX series? Or is it something else?
Thanks for any help!

**Comment by GabeRundlett** [comment]
Daxa does not require a raytracing capable GPU, however the latest master commit of gvox engine does. I'm closing this as unrelated to Daxa

**Comment by Ipotrick** [comment]
yea its unfortunate that we have these bad errors for device creation i ll look into that in the future
